### ISSUE TITLE
Question regarding OpenWow

### ISSUE THREAD

**Issue by redagito** [bouzi71/RemoteAccess#1]
Hi, 
I did not know how to contact you other than opening a ticket here.
I tried to compile your OpenWow project and I am missing the lib files libssl and libcrypto.
Can I ask you to provide me the ones you are using?
Also would you be interested in switching to CMake/Conan for the project (I would do a PR)?
Or in general, are you interested in collaborating on your OpenWow project? I noticed the Issue section is disabled

Kind regards

EDIT: I am pretty much missing all the required prebuilt libs for building TestApp

**Comment by bouzi71** [comment]
Hey, this is my project for education in 3d and c++, also i used it
for resume for work. If you want to compile it, you need:
- openssl lib (for client)
  https://slproweb.com/download/Win64OpenSSL-1_1_1a.msi
  https://slproweb.com/download/Win32OpenSSL-1_1_1a.msi
- freetype.dll (for each Debug/Release, copy files in bin_x86/Debug or
Release and bin_x64/Debug or Release
   https://www.freetype.org/download.html
- also you need wow 3.3.5a client (OpenWoW/main.cpp change path in
"std::shared_ptr<IFilesStorage> mpqFileStorage = ...") to you  WoW Data
folder
- also in this file change path to you repository _gamedata folder
"std::shared_ptr<IFilesStorage> localFilesGamedata = ..."

вт, 19 февр. 2019 г. в 13:11, Robert <notifications@github.com>:

**Comment by bouzi71** [comment]
I don't want use CMake, because this project only for education in 3D
graphics and i don't like it :)

чт, 21 февр. 2019 г. в 11:30, Alex Stenfard <alexstenfard@gmail.com>:

**Comment by bouzi71** [comment]
And now, unable to build this project, after fix build i will notife you
about it

чт, 21 февр. 2019 г. в 11:34, Alex Stenfard <alexstenfard@gmail.com>:

**Comment by redagito** [comment]
Hi, thanks for the reply, looking forward to how the project develops
